### ISSUE TITLE
advanced_part1에서 model_resolver component의 model_blessing관련 문의입니다.

### ISSUE THREAD

**Issue by eastjin218** [deep-diver/mlops-hf-tf-vision-models#6]
안녕하세요 
mlops를 학습하다가 코드를 찾게 되어 공부에 많은 도움이 되고 있습니다.
학습 수준별로 순차적으로 local 환경에서 테스트하고 있습니다.
문의 사항은
1. model_blessing에서 사용되는 모델이 현재 훈련된 모델끼리 비교가 하는 것 같은데 맞을까요??
2. 이전에 학습된 모델을 어떻게 model_resolver에서 load하는지 이해가 안되서요 혹시 방법을 알 수 있을까요?
3. repo 설명에 있는 그림처럼 test 파일을 이용한 비교를 할 경우 test파일만 이용해서 example_gen을 새롭게 만들어야 하나요??
문의전에 제공해주신 코드를 바탕으로 tensorflow document를 확인하였으나 어떻게 되는지 파악이 어려워서 문의드립니다.

**Comment by deep-diver** [comment]
안녕하세요! 문의 주신 질문에 답변을 드리자면,

1. model_blessing은 기본적으로 기존에 배포된 모델의 존재 여부에 따라 두 가지 비교를 합니다. 만약 아직 배포된 모델이 없다면, threshold 값에 따라 베이라인 모델로 통과될 최소 메트릭을 비교합니다. 만약 배포된 모델이 있다면, 현재 학습된 모델과 배포된 모델의 성능을 서로 비교합니다.

2. 기본적으로 모든 컴포넌트의 중간 결과물은 Artifact 라는 형태로, 디스크 어딘가에 저장됩니다. 그리고 저장된 Artifact와 파이프라인 Lineage 정보는 전통적인 RDB가 관리합니다 (로컬의 경우 SQLite). ModelResolver는 단순히, 가장 직전에 배포된(bless된) 모델 Artifact 정보를 DB에서 조회하여, 그 경로를 참조합니다. 물론 그 참조된 모델 경로를 따라가보면, 결국 SavedModel 형식으로 저장되어 있기 때문에 그대로 불러와 사용 가능한 것이구요.

3. ExampleGen은 파이프라인에 입력된 데이터를 원하는 대로 분리할 수 있습니다. 이 예제 Repo의 경우는 전체를 학습과 테스트 두 개로 분할했습니다. 그리고 분할된 결과물은 Artifact 형식으로 떨꿔지고, 사실은 TFRecord 형식의 파일로 디스크 어딘가에 저장되어 있습니다. 따라서 "ExampleGen 에게 테스트로 분할된 데이터를 줘" 라고 요청하면, 그 부분을 참조하는 내용을 얻을 수 있습니다. 

도움이 되었다면 좋겠네요 :)

**Comment by eastjin218** [comment]
답변 정말 감사합니다. 
아직 완전히 이해가 되지는 않지만 작성해주신 내용을 바탕으로 공부해서 추가로 문의 사항이 생기면 다시 문의 드리겠습니다 .
추가로 본 내용과 상관 없이 추가로 공부하다가 문의 사항이 생겼습니다.

개인적으로 local 환경의 ubuntu에서 단일 노드로 k8s와 kubeflow를 설치하여  kubeflow_runner.py를 수행하려고 합니다. 
1. 수행하기 위해서는 vertex Ai로 구성된 pipeline과 runner를 사용할수 있나요??
2. 사용이 가능하다면 같은 디렉토리에 있는 Dockerfile로 이미지를 build하고 build된 이미지로 kubeflow의 component함수를 새로 작성하여 pipeline을 만들어서 써야하나요??
